Repository dejan-xd-organization/NistagramOfflineAPI, pull requests merged in 2021-08, with the labels that each got.

#6 sonar_cloud -> develop Close #3
  Controllers/OfflineController.cs
  NistagramOfflineAPI.csproj
  Program.cs
  Properties/launchSettings.json
  Services/Interface/IOfflineService.cs
  Services/OfflineServiceImpl.cs
  Startup.cs
  bin/Debug/net5.0/Microsoft.IdentityModel.JsonWebTokens.dll
  bin/Debug/net5.0/Microsoft.IdentityModel.Logging.dll
  bin/Debug/net5.0/Microsoft.IdentityModel.Tokens.dll
  bin/Debug/net5.0/NistagramOfflineAPI.deps.json
  bin/Debug/net5.0/NistagramOfflineAPI.dll
  bin/Debug/net5.0/NistagramOfflineAPI.exe
  bin/Debug/net5.0/NistagramOfflineAPI.pdb
  bin/Debug/net5.0/NistagramOfflineAPI.runtimeconfig.dev.json
  bin/Debug/net5.0/NistagramSQLConnection.dll
  bin/Debug/net5.0/NistagramUtils.dll
  bin/Debug/net5.0/System.IdentityModel.Tokens.Jwt.dll
  bin/Debug/net5.0/ref/NistagramOfflineAPI.dll
  obj/Debug/net5.0/NistagramOfflineAPI.GeneratedMSBuildEditorConfig.editorconfig
  obj/Debug/net5.0/NistagramOfflineAPI.MvcApplicationPartsAssemblyInfo.cs
  obj/Debug/net5.0/NistagramOfflineAPI.assets.cache
  obj/Debug/net5.0/NistagramOfflineAPI.csproj.CoreCompileInputs.cache
  obj/Debug/net5.0/NistagramOfflineAPI.csproj.FileListAbsolute.txt
  obj/Debug/net5.0/NistagramOfflineAPI.dll
  obj/Debug/net5.0/NistagramOfflineAPI.genruntimeconfig.cache
  obj/Debug/net5.0/NistagramOfflineAPI.pdb
  obj/Debug/net5.0/apphost.exe
  obj/Debug/net5.0/ref/NistagramOfflineAPI.dll
  obj/NistagramOfflineAPI.csproj.nuget.dgspec.json
  obj/NistagramOfflineAPI.csproj.nuget.g.props
  obj/project.assets.json
  obj/project.nuget.cache
Labels: bug, documentation, pull request

#11 develop -> master Sprint 3 Release v1.0.2
  Controllers/OfflineController.cs
  NistagramOfflineAPI.csproj
  Properties/launchSettings.json
  Services/IOfflineService.cs
  Services/Implementation/OfflineServiceImpl.cs
  Services/Interface/IOfflineService.cs
  Services/OfflineServiceImpl.cs
  Startup.cs
Labels: user story, pull request, release

#13 feature/chat -> develop Feature/chat
  NistagramOfflineAPI.csproj
Labels: user story, pull request
